{
  parserClass="org.duckietown.hatchery.rosinterface.RosInterfaceParser"
  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiImplClassSuffix="Impl"
  psiClassPrefix="RosInterface"
  psiPackage="org.duckietown.hatchery.psi"
  psiImplPackage="org.duckietown.hatchery.psi.impl"

  elementTypeHolderClass="org.duckietown.hatchery.psi.RosInterfaceTypes"
  elementTypeClass="org.duckietown.hatchery.psi.RosInterfaceElementType"
  tokenTypeClass="org.duckietown.hatchery.psi.RosInterfaceTokenType"
}

rosInterfaceFile ::= (property|COMMENT|CRLF)*

property ::= (TYPE KEY SEPARATOR VALUE)|(TYPE KEY) {
    pin=3
    recoverWhile="recover_property"
    mixin="org.duckietown.hatchery.psi.impl.RosInterfaceNamedElementImpl"
    implements="org.duckietown.hatchery.psi.RosInterfaceNamedElement"
//    methods=[getType getKey getValue getName setName getNameIdentifier]
}

private recover_property ::= !(TYPE|KEY|SEPARATOR|COMMENT)